_defaults:
  - "configs/models/vitdet_b_argoverse.yml"
margin: 0
period: 4
conf: 0.5
sparsity: 0.9
keep_rate: 1.0
window_drop: false
_output: "results/evaluate/argoverse_hd/${_name}/"
output_weights: "results/train/argoverse_hd/${_name}/weights_latest.pth"
dataset:
  name: "argoverse_hd"
  root: "./data/argoversehd"
  split: "val"
  annotations: "./data/argoversehd/Argoverse-HD/annotations/val.json"
split: "val"
dataset_type: "argoverse_hd"
vanilla: false
weights: "weights/vitdet_b_argoverse.pth"
evaluate: true

